### ISSUE TITLE
Hacked address because of resend from address with pending transactions

### ISSUE THREAD

**Issue by ole-olafson** [iotaledger/android-wallet-app#127]
In short: One of my addresses was hacked. The seed is save: only a single address is compromised.

Most probable reason: Android wallet allows resend of unconfirmed Iotas. This seems to result in multiple outputs with the related decrease in safety. In this case I performed a total of three attempts to transfer my Iotas, because of the pending status and by using different destination adresses. Directly after the 3rd attempt, the theft kicked in with a massive attack (over 600 trials). Btw, I reattached my original transaction 4 times without success.

Should the Android wallet prevent such resends or at least give a warning? 
I hope this can be fixed soon! Let me know if you need further information.

Robbed Address:
800.8 Mi   JBOAHCNBHP9FORPYAFWONRU9WANWFOAAQBDIYRHO9BOLXCGANVXGEGTECTOGDHZEM9ODCZEYCOVSS9ZP9PWVAOTZSX

Stolen Iota transfered to:
400.4 Mi   BAXUZY99UFMNEGXIJJYGDDTQKPFDQUDVYGXKAPWZIHPYHEVCSZRQARDLVDXUCDPTKYTBMJGMQIVZDKPODNJHKFOGXX
400.4 Mi   ZKPQIN9SEKFJLLCWEJSJPPTSNIWDZJCXEZDJVQMQQBHFKJFUJWE9SMJYBKKZHTILKDHEHFOEGXEUVYXSDZNUNCUXVW

**Comment by emalaj** [comment]
+1 happened to me with basically the exact same repro steps. Are all iota at that address actually lost or are they safe so long as the seed is safe? Any way to cancel or override these multiple pending withdrawals?

**Comment by emalaj** [comment]
In my case, all fraudulent outbound transactions were still pending (for many hours), so I spammed the network with my own transfers of the entire wallet balance to new addresses and, for reasons I don't understand, one of my transactions was confirmed within minutes, and before one of the hacker's, so I was able to recover all of my funds. 

Most people may not be as lucky as I -- this type of protocol weakness + wallet bug is truly unacceptable and needs to be addressed.

**Comment by ole-olafson** [comment]
Nice that you was able to outsmart them! I was not that lucky, the attack was too heavy.
And I agree on the need to fix this to prevent others from making the same mistake.

Btw. I like the Android wallet (design and usability) and would be glad if this is solved.

**Comment by Parmacoy** [comment]
For me, 2.11Gi stolen, and Confirmed stolen. The wallet was not actually sending my transactions over days. So I tried again with the Replay bundle feature. Had a semi large 83 transaction attack before. Someone got it before I could try spam it and get it back. All gone...

Lost a lot of faith in IOTA because of this

**Comment by ole-olafson** [comment]
Hey Prem, thats sad! Hope only one of your addresses was compromised.

While reattaching respectively 'replay bundle' in the the Android wallet is considered as the only save way to push a transaction, this behavior is strange. Would you mind to share the related address to get some more details?

**Comment by pinpong** [comment]
fixed with 36a1d6

**Comment by Parmacoy** [comment]
Hi @pinpong, can you please explain how the issue is fixed? I am still quite irate over losing 2.11Gi through just using the app. Please explain how it was exploited, and how it has been resolved (so that what I experienced does not happen to others). As I know I will never be able to recoup that money I lost.

**Comment by Parmacoy** [comment]
HI @pinpong, since it sounding like the app was the fault of my losing all of my funds. I think it fair that I be reimbursed for what was stolen. I did my due diligence, and through using of the software, lost my entire holdings.

**Comment by pinpong** [comment]
Are you a dev then take a look at https://github.com/iotaledger/iota.lib.java/commit/6c2df379596eb3c9791badea1cfb98a583c6e84d

**Comment by Parmacoy** [comment]
I am a dev, however not experienced with the tangle. I along with others would like to know how this happened. Surely you can provide an explanation considering the situation. A summary of sorts, so that I don't need to read the source code to understand the cause and effect.

**Comment by Parmacoy** [comment]
For more context, you can refer to the following reddit thread. [](https://www.reddit.com/r/Iota/comments/7e0gu8/186gi_stolen_from_android_wallet/)

**Comment by ole-olafson** [comment]
Thanks for the implementation, Pinpong! 
But I agree with Parmacoy, a few words about the applied changes would be nice (for those of us having difficulties with the code :-)

**Comment by adrianziser** [comment]
Adrian Z:
A short reminder for everyone complaining about lost funds atm. It's not the fault of the app that you don't understand why a One Time Signature implies that you should only use them once. That's not perfect for a normal user, true, but the software was marked as beta, there is even a disclaimer that you could lose all your money if you don't know what you're doing. Like the normal wallet we know prevent wrong / false behaviour on the user side and I think it's a good thing. But it's important that user understand the major, conceptional difference between iota and other (legacy) blockchain projects. Sadly most of you guys are interested in making money and not the technology itself. If you're sending money out to the wrong recepient you can't blame your bank for that, if you are reusing addresses although everybody told you not to do so, guess what, it's also your own fault. The app was not malicious or vulnerable, we simply expected that users are able to read and understand the basic and underlying concepts of iota. Yes, we now added prevention measures to solve this kind of misbehavior, but it's still the same, a kind of user driven misbehavior

**Comment by Parmacoy** [comment]
Hi @adrianziser, I understand that its beta, also understand the risks. I was under the impression that I did not do address reuse. Rather, I was using the "Replay Bundle" feature to try and push a 200Miota transfer to bitfinex. Now, I am also a bit confused then, with the Send Iota Button, where you specify the receiving address and the amount, does that create a new address, as if not, it is not clear how to create a new address. Otherwise, I did my due diligence, and through the Replay Bundle feature, it instead did the address reuse. Thanks for your answer btw. Just as a dev and an advocate for IOTA, I would love to know what specifically I did wrong, so that I make sure to learn from, and not do it again.

Thanks

**Comment by ole-olafson** [comment]
That's ok for me. Users are warned if they are about to harm the integrity of an address by reusing it - perfect! 

Does this also apply for after-snapshot address reuse or is covering this impossible?

**Comment by pinpong** [comment]
@ole-olafson without a external database or a permanode  this is currently not possible.

**Comment by adrianziser** [comment]
That's the point and still a potential risk for normal wallet and app users. If Alice empties her seed before a snapshot occurs and decides to continue to use it after that, you will see the exactly same attacks and there is nothing we can do about it right now. That's one of the reason why I thought it's better for the people to learn it the hard way. And don't get me wrong, I hate the fact that people lost money & that there are people exploiting this all of the time. But during the last week we received threats, people wanted to sue us, blamed us for producing fraudulent software and I really wanted to express my / our point of view.

**Comment by ole-olafson** [comment]
I like the principal idea of having a stateless wallet. Nevertheless this might be one of the critical points for inexperienced users. But that's another topic.

**Comment by ole-olafson** [comment]
Adrianizer, did I get that right and you implemented a warning in the upcoming app version? Or is resending of a pending transaction to a different address disabled now?

**Comment by Parmacoy** [comment]
Hi @adrianziser, apologies for my terseness prior. I am still a bit raw with the loss of funds. What I just want is for this vulnerability to be catered for in software so that it does not happen to the average user. The fact that the IOTA Tangle is quite complicated. I am merely trying to understand the scenario that led to this, and to understand in a more technical point. Thanks for creating the software, but also from a Users Point-Of-View for the 3 days prior to the theft, I had no luck transferring any funds outside of the wallet into Bitfinex. Every transaction was pending. This was even when I had changed nodes over to various different ones, hoping for a confirmation. Also this was with Local POW switched on, and off as well. I tried all available permutations, but with no avail. So that also concerned me, that I could send money to, but failed to send money out of.

That is the biggest gripe with it so far.

**Comment by funkyfranz** [comment]
Same here, 6.75 Gi were stolen from my android wallet app with the same procedure. I had a couple of transactions to bitfinex which were pending unconfirmed because of the Denial of Service attack to the iota network. I tried fiddeling with all the functions and settings of the wallet app in order to get my transactions confirmed. Among those, unfortunately, there was the "resend" function, which weakens crypto without a warning compromising my private key. Looking at the tangle explorer, there were probably two different attackers trying to empty my wallet. one of them started a bit earlier, but the second one succeded getting a transaction confirmed, because he fired transactions at a higher rate. (several hundred of them, one attempt every 15 seconds approximately). Now I am left with a balance of 0i, and no way to recover my funds.

**Comment by ole-olafson** [comment]
This sounds very familar to me - you have my sympathy!

**Comment by ole-olafson** [comment]
While the average user seemed to be unable to react in such a situation or not even recognises the danger, the following idea crossed my mind: Some good guys (e.g. the Iota Foundation) could save the day!

Try to get Iotas off vulnerable addresses in priciple with the identical procedure. Inform the owner that they should provide a new address for delivery of the saved Iotas (should be possible via the tag or signature of an transaction back to the weak address). Send the Iotas back, tagged with an address for the reward - or find another agreement on this.

Just dreaming =D

I would even spend one third of my lost fund if it would be handed back - without complaining!

**Comment by Parmacoy** [comment]
That would be a continuous fight though @ole-olafson, White-Hat Hackers versus Black-Hat Hackers. The Black-Hat hackers would just find a way to do it faster, with more resources before the foundation.

I just feel duped that the circumstances which led us to lose all our funds was really out of our control. Furthermore, the research I did when finding out that people's transactions were pending was to do the "Replay Bundle" feature. Which I thought was the safe way. The fact that we all lost our funds through no real fault of our own, through the app, really sucks. Sorry for your loss of funds @funkyfranz. I just wish it were possible to reclaim such things, as it was proving to be my most profitable investment... No longer. I have my hopes set on Ripple (XRP) now. At least its more secure than this system...

**Comment by ole-olafson** [comment]
@Parmacoy, I guess you are right about this fight between the good and the bad.

Regarding the 'Replay bundle' feature: Would you mind to share the related address to get some more details? I would really like to figure out if this causes the problem. In my case for sure the theft was related to the 'resend' option!

**Comment by pinpong** [comment]
@ole-olafson what do you mean with the resend option?

**Comment by ole-olafson** [comment]
From my first post:
> Android wallet allows resend of unconfirmed Iotas

**Comment by pinpong** [comment]
@ole-olafson That was also possible with the Desktop Wallet. It was not a bug and the patch served only for improvement.

**Comment by ole-olafson** [comment]
@pinpong, the implementation of this warning was my initial intention to open this thread. Thank you once again for realizing that so fast!

And of course the resend option itself is no bug and should be further available because it might be needed (even if using it is not recommended)!
