### ISSUE TITLE
Network error/iota wallet 

### ISSUE THREAD

**Issue by gnewlun** [iotaledger/android-wallet-app#141]
Description:
---

Can't connect to wallet because it keeps saying network error .

Device info:
---
<table>
<tr><td>App version</td><td>0.9.109-32ea8fb</td></tr>
<tr><td>App version code</td><td>90109</td></tr>
<tr><td>Android build version</td><td>G955USQU1AQJH</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G955USQU1AQJH</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dream2qltesq</td></tr>
<tr><td>Device model</td><td>SM-G955U</td></tr>
<tr><td>Device product name</td><td>dream2qltesq</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Sorry but it is network dependent.

**Comment by hannesa2** [comment]
Independent, if it's a network error or not, with this, the complete IOTA story is not use able and obsolete.
Since two weeks I try to send a test amount of IOTA to this wallet, but with network errors I'm not able and even I don't want to transfer some IOTAs.

How to solve it ?
Are there other working nodes ? 

Btw, because of this I sold almost all my IOTA, because it's just an empty promising improvement to crypto currencies
